Update Rust edition
glium/glium pull request #1886
Opened 2020-10-23 18:36 UTC by agluszak

This PR changes the edition of Rust used by glium to 2018. It consists almost exclusively of auto-fixes generated by `cargo fix` and `clippy`.  This is my first contribution to a Rust crate :)

Why? I started learning both Rust and OpenGL. When I was following the tutorial from [the book](https://github.com/glium/glium/tree/master/book), I noticed that it was slightly out of date. So I started updating it. I will submit a separate PR with the new version. But then I noticed that the crate itself uses 2015 edition and I thought: "Oh, maybe I could do something with that as well" :)

2020-10-23 20:46 UTC, est31 requested changes
Will accept the PR if the `is_empty` changes are reverted and the `extern crate` lines are removed instead of being blanked.

2020-10-23 20:46 UTC, est31 commented on examples/support/mod.rs
> +
Why do you replace the `extern crate` statements with empty lines? If you remove them, please also remove the line.

2020-10-23 20:46 UTC, est31 commented on tests/shaders.rs
> +    assert!(!binary.content.is_empty());
I think the `is_empty` lint of clippy is misguided/harmful. The older code was shorter as well as clearer.

2020-10-24 09:21 UTC, est31 commented
Can you revert all `is_empty` calls? And can you squash the `is_empty` relating commits into the commits that introduced the `is_empty` changes to keep blame intact? Thanks.

2020-10-24 09:21 UTC, agluszak commented
Fixed! I didn't notice the blank lines, they were introduced by `cargo fix`

2020-10-24 12:19 UTC, est31 requested changes
I'd love a revert of these changes, right inside the commit that changed them to keep the diff intact. Do you know how to do that? Otherwise check out `git rebase -i`.

2020-10-24 12:19 UTC, est31 commented on src/context/mod.rs
> +    if result.is_empty() {
is_empty

2020-10-24 12:19 UTC, est31 commented on src/program/reflection.rs
> +            if result.is_empty() {
is_empty

2020-10-24 13:08 UTC, agluszak commented
I squashed all commits into one, I thought it could be done while merging :) Hopefully it's all okay now

2020-10-24 13:11 UTC, est31 approved these changes
Thanks!

2020-10-24 13:47 UTC, merged