add cubemap support
glium/glium pull request #1957
Opened 2021-08-29 07:00 UTC by JerryChCN

implement cubemap binding with texture3d. it's the easist way if don't refactor the texture. the project doesn't have example showing how to test it correctly, so it may have some problems or bugs.

2021-08-29 15:00 UTC, est31 commented on src/texture/mod.rs
> +            if i.width != i.height {
Can this be an assert_eq instead? assert_eq can emit a format string too.

2021-08-29 15:05 UTC, est31 requested changes

2021-08-29 15:05 UTC, est31 commented on src/texture/mod.rs
> +        if data.width != data.height { panic!("width does't equal height"); }
assert_eq

2021-08-29 15:05 UTC, est31 commented on src/texture/mod.rs
> +/// wrap RawCubemap in RawImage3d
```suggestion
/// Wraps a RawImage3d into a cube map
```

2021-08-29 15:05 UTC, est31 commented on src/texture/any.rs
> +                let mut cube_data_raw = if let Some((_, ref data)) = data {
Can't you just use an unwrap here? Maybe `.ref().unwrap()`?

2021-11-24 11:18 UTC, est31 commented
@JerryChCN hi have you seen my review comments? If you want this pull request to be merged, please address them.

2022-10-17 16:52 UTC, panda2134 commented
Hi! Is there any chance for this PR to be merged?

2022-10-26 13:40 UTC, est31 commented
Closing because no response. If the comments are addressed, I would love to see another PR!

2022-10-26 13:40 UTC, closed without merging