Validate that a framebuffer isn't 0 on any dimension
glium/glium pull request #2051
Opened 2023-04-01 16:49 UTC by Melchizedek6809

I've added a check during framebuffer creation that makes sure that it's not 0 on any dimension, since this would lead to other errors later, now we return a ValidationError::EmptyFramebufferUnsupportedDimensions in that case.

Since on Windows one can resize a window to have 0 width/height which also happens when minimizing I've changed the fxaa example so that it doesn't crash on Windows (Mac and Linux with various WMs seem to ensure that a window is alwasy at least 1x1)

This fixes https://github.com/glium/glium/issues/2044

2023-04-01 20:58 UTC, est31 requested changes

2023-04-01 20:58 UTC, est31 commented on examples/fxaa.rs
> +        // happen when you minimize/resuze the window on Windows for example.
typo

2023-04-01 21:15 UTC, Melchizedek6809 commented on examples/fxaa.rs
> +        // happen when you minimize/resuze the window on Windows for example.
Ah my bad, I amended the commit.

2023-04-02 03:37 UTC, est31 approved these changes
Thanks!

2023-04-02 03:37 UTC, merged